adversary_list: []
alpha_loss: 1.0
baseline: false
batch_size: 64
clamp_value: 1.0
current_time: Feb.08_21.21.44
decay: 0.0005
diff_privacy: false
dirichlet_alpha: 0.9
environment_name: ppdl_experiment
epochs: 10100
eta: 1
fake_participants_file: data/reddit/updates_cifar.pt.tar
fake_participants_load: false
fake_participants_save: false
folder_path: saved_models/model_image_Feb.08_21.21.44
is_poison: false
log_interval: 10
lr: 0.1
modify_poison: false
momentum: 0.9
no_models: 10
noise_level: 0.01
number_of_adversaries: 1
number_of_total_participants: 100
poison_decay: 0.005
poison_epochs:
- 10000
poison_image_id: 2775
poison_image_id_2: 1605
poison_images:
- 30696
- 33105
- 33615
- 33907
- 36848
- 40713
- 41706
poison_images_test:
- 330
- 568
- 3934
- 12336
- 30560
poison_label_swap: 2
poison_lr: 0.05
poison_momentum: 0.9
poison_step_lr: true
poison_test_repeat: 1000
poison_type: wall
poisoned_number: 2
poisoning_per_batch: 1
random_compromise: false
report_poison_loss: false
report_test_loss: false
report_train_loss: false
results_json: false
resumed_model: null
retrain_no_times: 2
retrain_poison: 15
s_norm: 1000000
sampling_dirichlet: true
save_model: false
save_on_epochs:
- 10
- 100
- 500
- 1000
- 2000
- 5000
scale_weights: 100
size_of_secret_dataset: 200
test_batch_size: 1000
track_clusters: false
track_distance: false
type: image
